name: Create deployment

on: 
  pull_request:
    types: [labeled]
  checks: 
    types: [complete]

jobs:
  deploy:
    name: "deploy"
    runs-on: ubuntu-latest
    steps:
    - uses: SvanBoxel/deploy@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
