name: Create deployment

on: 
  pull_request:
    types: [labeled]

jobs:
  deploy:
    name: "deploy"
    runs-on: ubuntu-latest
    steps:
    - uses: SvanBoxel/deploy@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
